general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ["shell-exec %userprofile%/.glzr/zebar/start.bat"]

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "window_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "8px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "68px" # for the bar
    right: "8px"
    bottom: "8px"
    left: "8px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  # # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  # - commands: ["set floating"]
  #   match_class_name: "#32770"

  - commands: ["set-floating"]
    match:
      # 1password
      - window_process: { equals: "1Password" }

      # sticky notes
      - window_title: { regex: "^付箋$" }
        match_class_name: { equals: "ApplicationFrameWindow" }

      # explorer
      - window_process: { regex: "explorer|Files" }

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - commands: ["resize --width -2%"]
        bindings: ["H", "Left"]
      - commands: ["resize --width +2%"]
        bindings: ["L", "Right"]
      - commands: ["resize --height +2%"]
        bindings: ["K", "Up"]
      - commands: ["resize --height -2%"]
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["Alt+H"]
  - commands: ["focus --direction right"]
    bindings: ["Alt+L"]
  - commands: ["focus --direction up"]
    bindings: ["Alt+K"]
  - commands: ["focus --direction down"]
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["Alt+Shift+H"]
  - commands: ["move --direction right"]
    bindings: ["Alt+Shift+L"]
  - commands: ["move --direction up"]
    bindings: ["Alt+Shift+K"]
  - commands: ["move --direction down"]
    bindings: ["Alt+Shift+J"]

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["Alt+R"]

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["Alt+V"]

  # Change focus between floating / tiling windows.
  - commands: ["wm-cycle-focus"]
    bindings: ["Alt+Space"]

  # Change the focused window to be floating / tiling.
  - commands: ["toggle-floating --centered"]
    bindings: ["Alt+Shift+Space"]

  # Change the focused window to be maximized / unmaximized.
  - commands: ["toggle-fullscreen"]
    bindings: ["Alt+M"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["Alt+Shift+M"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["Alt+Shift+Q"]

  # Kill GlazeWM process safely.
  - commands: ['shell-exec taskkill /IM "zebar.exe" /F', "wm-exit"]
    bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands:
      [
        "wm-reload-config",
        'shell-exec taskkill /IM "zebar.exe" /F',
        "shell-exec %userprofile%/.glzr/zebar/start.bat",
      ]
    bindings: ["alt+shift+r"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["Alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["Alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["Alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["Alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["Alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["Alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["Alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["Alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["Alt+9"]

  # Move focused workspace to a monitor in a given direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["Alt+Left"]
  - commands: ["move-workspace --direction right"]
    bindings: ["Alt+Right"]
  - commands: ["move-workspace --direction up"]
    bindings: ["Alt+Up"]
  - commands: ["move-workspace --direction down"]
    bindings: ["Alt+Down"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["Alt+Shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["Alt+Shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["Alt+Shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["Alt+Shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["Alt+Shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["Alt+Shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["Alt+Shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["Alt+Shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["Alt+Shift+9"]

  # -------------------------
  # applications
  # -------------------------
  # Launch terminal
  - commands:
      [
        "shell-exec %USERPROFILE%/scoop/apps/wezterm-nightly/current/wezterm-gui",
      ]
    bindings: ["Alt+Enter"]

  # Launch browser
  - commands: ["shell-exec explorer http://"]
    bindings: ["Alt+F2"]

  # Launch 1password
  - commands:
      ["shell-exec %LOCALAPPDATA%/1Password/app/8/1Password.exe --quick-access"]
    bindings: ["Alt+O"]

  # Launch explorer
  - commands: ["shell-exec explorer"]
    bindings: ["Alt+E"]
# bar:
#   height: "40px"
#   position: "top"
#   opacity: 1.0
#   background: "#414459"
#   foreground: "#c6d0f5"
#   font_family: "UDEV Gothic NF"
#   font_size: "12px"
#   padding: "4px 6px"
#   offset_x: "0"
#   offset_y: "0"
#   border_radius: "0"
#   components_left:
#     - type: "workspaces"
#       focused_workspace_background: "#babbf1"
#       displayed_workspace_background: "#00000033"
#       default_workspace_background: "transparent"
#   components_center:
#     - type: "window title"
#   components_right:
#     - type: "network"
#       margin: "0 4px 0 0"
#
#     - type: "battery"
#       margin: "0 4px 0 0"
#       label_draining: "󰂂 {battery_level}%"
#       label_power_saver: "󰂂 {battery_level}%"
#       label_charging: "󰂋 {battery_level}%"
#
#     - type: "system tray"
#       margin: "0 4px 0 4px"
#       padding: "4px 0"
#       label_expand_text: "<"
#       label_collapse_text: ">"
#
#     - type: "tiling direction"
#       label_horizontal: "⮂"
#       label_vertical: "⮁"
#       background: "#ffffff33"
#       margin: "0 4px"
#       padding: "0 8px"
#
#     # - type: 'binding mode'
#     #   background: '#ffffff33'
#     #   margin: '0 4px 0 0'
#     #   padding: '0 8px'
#
#     - type: "clock"
#       font_size: "12px"
#       time_formatting: '   HH:mm:ss\nyyyy年MM月dd日'
