pulse.cmd = [
    {
        cmd = "load-module"
        args = "module-loopback source=alsa_input.usb-AVerMedia_Live_Gamer_Ultra_2.1_5314056900637-02.analog-stereo sink=alsa_output.usb-Jieli_Technology_USB_Composite_Device_4250315A35353802-01.analog-stereo latency_msec=0 source_dont_move=true sink_dont_move=true"
        flags = [ nofail ]
    }
]
