pulse.cmd = [
    {
        cmd = "load-module"
        args = "module-loopback source=alsa_input.usb-AVerMedia_Live_Gamer_Ultra_2.1_5314056900637-02.analog-stereo latency_msec=30 source_output_properties=node.dont-fallback=true"
        flags = [ nofail ]
    }
]
